# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
            21    # Latest version
        ]
        # and run on both Linux and Windows
        os: [ ubuntu-latest, windows-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew build
      - name: SHA256 Checksum
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }} # Only checksum artifacts built from LTS java on one OS
        run: |
          sha256sum fabric/build/libs/* | sed 's|fabric/build/libs/||' >> sha256-fabric.txt
          sha256sum neoforge/build/libs/* | sed 's|neoforge/build/libs/||' >> sha256-neoforge.txt
      - name: Publish Checksum Output to Summary
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }} # Only upload artifacts built from LTS java on one OS
        run: |
          {
            echo "### Artifact SHA256"
            echo '```terraform'
            echo '# Fabric`
            cat sha256-fabric.txt
            echo '# Neoforge'
            cat sha256-neoforge.txt
            echo '```'
          } >> $GITHUB_STEP_SUMMARY
      - name: Add Gradle Summary Title
        run: echo "### Gradle Summary" >> $GITHUB_STEP_SUMMARY
      - name: Capture fabric build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }} # Only upload artifacts built from LTS java on one OS
        uses: actions/upload-artifact@v4
        with:
          name: fabric-builds
          path: fabric/build/libs/
      - name: Capture neoforge build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }} # Only upload artifacts built from LTS java on one OS
        uses: actions/upload-artifact@v4
        with:
          name: neoforge-builds
          path: neoforge/build/libs/
